### ISSUE TITLE
Remove checker's runtime dependence on lombok jar

### ISSUE THREAD

**Issue by msridhar** [kelloggm/typesafe-builder-checker#39]
Unfortunately, Lombok does not distribute an annotations jar.  Since we are doing some runs with annotation processor auto-discovery, this means that when we run our checker, Lombok also gets run, which slows down the checker and could have unanticipated consequences.  It's not ideal, but we should probably use a strings to identify Lombok annotations to get rid of this dependence.

**Comment by kelloggm** [comment]
Good catch - I didn't consider that. I'll work on removing the dependency.
